runtime: python39


instance_class: F2

env_variables:
  FLASK_APP: "main.py"
  FLASK_DEBUG: "1"
  FLASK_RUN_PORT: "8080"
  FLASK_RUN_HOST: "0.0.0.0"
  MYSQL_IP: "34.74.128.154"
  MYSQL_USER: "root"
  MYSQL_PASS: "7NpRP.Y==NgL8pnQ"
  MYSQL_DB: "AdCampaignManager"
  MAIL_CLIENT_ID: "614960797057-ji2eum9i450tf7i00nr5m6avkgoa199c.apps.googleusercontent.com"
  MAIL_CLIENT_SECRET: "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"
  MAIL_REFRESH_TOKEN: "1//04hrkYwcyQ7TGCgYIARAAGAQSNwF-L9IrGiyTsn0yzUFqWLmvHkkGWLaQPtw5BBZq-8fAd2KQzEavYXTKtHRmRMw3514y6JhJscc"
  IMGUR_CLIENT_ID: "5331f6b5050b43c"
  IMGUR_CLIENT_SECRET: "cbf7c682172de23f039b73ba64b75dee9882ab6b"
  MAIL_USERNAME: "a.i.ads.csc400@gmail.com"
  MAIL_APP_PASSWORD: "csc400djd"
  MAIL_SENDER_NAME: "CampAIgn Manager"
  PYTHONDONTWRITEBYTECODE: "1"
  OPENAI_API_KEY: "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"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /static
  static_dir: app/static
- url: /.*
  script: auto
